"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.SCROLLABLE_STATE = void 0;
let SCROLLABLE_STATE;
exports.SCROLLABLE_STATE = SCROLLABLE_STATE;
(function (SCROLLABLE_STATE) {
  SCROLLABLE_STATE[SCROLLABLE_STATE["LOCKED"] = 0] = "LOCKED";
  SCROLLABLE_STATE[SCROLLABLE_STATE["UNLOCKED"] = 1] = "UNLOCKED";
  SCROLLABLE_STATE[SCROLLABLE_STATE["UNDETERMINED"] = 2] = "UNDETERMINED";
})(SCROLLABLE_STATE || (exports.SCROLLABLE_STATE = SCROLLABLE_STATE = {}));
//# sourceMappingURL=constants.js.map